# Site settings
title: Technical Musings
email: suzanne.matthews@usma.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my GitHub paages site! I will be updating this site with 
  both technical documentation and teaching materials. Please contact me 
  if you are interested in potentially collaborating on projects or have 
  any questions. Thank you for visiting!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  suzannejmatthews
highlighter: true
timezone: "America/New_York"
# Build settings
markdown: kramdown
